### ISSUE TITLE
Update RMap domain model to support java.io.Serializable

### ISSUE THREAD

**Issue by emetsger** [rmap-project/rmap#118]
With the `IdService` [removed](#115) from the domain model, the path is clear for the elements of the model to support `java.io.Serializable`.

Updating the model to support `Serializable` will allow serialization of the objects in the domain model to bytes using `ObjectOutputStream` and `ObjectInputStream`, which provides another avenue to object (de)serialization in addition to JSON and RDF.  Native JVM serialization is nice, because you get a lot of things for free, though there are concerns if we were to use the JVM serialization for long-term storage (e.g. issues with binary compatibility of serialized objects between versions of the JVM).

The use case is to support writing Java objects to a Kafka journal for the purposes of indexing.  I envision the journal being transient, and replaceable.  For example, a re-indexing operation would be able to re-create the log.  The existing RDF model could have worked, but probably would have taken more space in the log (though compression could be supported).

At any rate, by supporting `Serializable` we'll get native serialization of java object graphs, which should be pretty speedy.  Tests can insure that the graph of domain objects can be successfully (de)serialized as the codebase evolves.  If we decide to distance ourself from JVM serialization in the future, the RDF serialization should be a viable, albeit bulkier and slower, alternative.

**Comment by karenhanson** [comment]
@emetsger Is this now closed by PRs #119 & #120?

**Comment by emetsger** [comment]
@karenhanson Yes!  Closing!
