### ISSUE TITLE
Docker containers should not load if tests skipped

### ISSUE THREAD

**Issue by karenhanson** [rmap-project/rmap#223]
When using -DskipTests, docker containers still load even though they are not used. This adds time to build and sometimes leaves the docker instances running.

**Comment by emetsger** [comment]
@karenhanson to skip `docker-maven-plugin` execution, try: `-Ddocker.skip`.  See [here](https://dmp.fabric8.io/#global-configuration) for more info (and other "skip"-related settings).

`-DskipTests` doesn't affect the docker maven plugin, at least, by default.

**Comment by emetsger** [comment]
Also, docker containers shouldn't _randomly_ be left running.  They may be left running in the case of an aborted build, but otherwise they should stop successfully.  If they don't stop, please comment here with the build output and the circumstances, and I can take a deeper look.

**Comment by karenhanson** [comment]
@emetsger OK, thanks for clarification. Will use the docker.skip. I may add a line to documentation for this too.  I think the container not shutting down might have been the result of changing the war file name before the docker container was finished starting and stopping, but yes, it also happens if I skip tests and the build fails.
