### ISSUE TITLE
Best practice: Add document on general rules for formatting URIs

### ISSUE THREAD

**Issue by htpvu** [rmap-project/rmap#33]
On the RMap tech wiki, add a document describing some general rules for formatting URIs. Identify common persistent identifier types and document rules for formatting those as well.

**Comment by karenhanson** [comment]
Closing this, it will continue to evolve as we get feedback 
https://rmap-project.atlassian.net/wiki/spaces/RMAPPS/pages/198475777/RMap+DiSCO+Best+Practices
