### ISSUE TITLE
Stability, security: Re-evaluate triplestore / graphdb technology.

### ISSUE THREAD

**Issue by cyork** [rmap-project/rmap#42]
Re-evaluate triplestore / graphdb technology. Do we want to stay with what we have for production, subscribe to the enterprise edition, or seek different solutions?  Note that migrating from sesame/openrdf api support will result in quite a large (but not inconceivable) code change.  

We should at least upgrade to the latest version of GraphDB which is now 2 versions ahead of the one we have

**Comment by karenhanson** [comment]
A much newer has been tested and is installed using the [RMap Shell Installer script](https://github.com/rmap-project/rmap-shell-installer/blob/master/rmap-installer/install_graphdb.sh).  Now that we have verified that installing identical copies of GraphDB from a script is possible, and we have not found any serious performance issues, we can close this task. If we run into performance issues later during testing we will re-open.
