### ISSUE TITLE
 Write list of requirements/use cases for indexer integration. 

### ISSUE THREAD

**Issue by htpvu** [rmap-project/rmap#52]
This should be done by the team, led by one person to ensure we capture all of the requirements for an indexer that we'll implement for RMap

**Comment by karenhanson** [comment]
Some preliminary notes here: https://docs.google.com/document/d/1gJvDETOQ_QuJ6ncAYAjIXl1WP_3klXq4ELoZrqWlZyU

**Comment by karenhanson** [comment]
First version of indexer complete. Was implemented with DiSCO search only. Future implementation may include Resource Summary indexing if deemed necessary. For now will close this.
