### ISSUE TITLE
Evaluate gaps in both unit and integration tests. Improve coverage of tests.

### ISSUE THREAD

**Issue by htpvu** [rmap-project/rmap#60]
This work is in progress by @karenhanson 
https://docs.google.com/document/d/16geft0p-x4Ro-wjpLd4TlhNlRjv5LfGU1ySGvEki6zE/edit#

To be continued

**Comment by karenhanson** [comment]
Evaluated for gaps, per above doc, but only wrote several tests before other priorities took precedent. Removing myself as an assignee in case anyone else wants to work on this until I get back to it.

**Comment by karenhanson** [comment]
A lot of work done around this. It is an ongoing process rather than a discrete task at this point. Further work should be defined as specific tasks.
