### ISSUE TITLE
Discuss with team and make decisions on user management process

### ISSUE THREAD

**Issue by htpvu** [rmap-project/rmap#64]
This include deciding and documenting who has access to deposit data into RMap, which authentication mechanism is used etc.

Relating to Workplan task 3.7.5

**Comment by karenhanson** [comment]
Discussion held 8/10/2017. Decided to keep the current user management but (1) make it more configurable/be able to switch options on and off in a way that it is reflected in the GUI (2) add an admin tool to manage all users, something that could be used for mediated access (3) look into adding InConnected auth option (4) provide GUI through which a user can create a DiSCO to represent their Agent during setup. (5) provide some options for local branding of RMap system and individual RMap users.
