### ISSUE TITLE
Simplify node labels on visualization.

### ISSUE THREAD

**Issue by htpvu** [rmap-project/rmap#68]
Currently node labels display the node URI. It would be easier to read nodes if these labels were replaced with e.g. foaf:name, rdf:label, dct:title, where available.

see tasks 3.7.8 in the workplan for mock up https://docs.google.com/document/d/12BCMVxFRlewjNLnUPEUyqEi4NA3rJ7kXivcce8KGbO8/edit#

**Comment by karenhanson** [comment]
Included in PR #194
